### ISSUE TITLE
Could you confirm input format?

### ISSUE THREAD

**Issue by BartWolk** [HanGuo97/soft-Q-learning-for-text-generation#1]
Hi, 

thanks for this promising paper and the entire repo.

I would like to reproduce the results for controllable text generation and would like to confirm what is format of sources and targets file. 

In the source file, I should provide topics from PPLM paper, and in the target file prompts - combined from keywords allocated to the particular topic + treat this combination with rephrase model (Pegasus). Am I right?

[sources.txt](https://github.com/HanGuo97/soft-Q-learning-for-text-generation/files/6764067/sources.txt)
[targets.txt](https://github.com/HanGuo97/soft-Q-learning-for-text-generation/files/6764069/targets.txt)

And as I understand - the entire exercise is to create prompt generator model from scratch, and its tokenizer may differ  from the original GPT2 implementation may differ, am I right? 

The reason why I am asking this question, is because class `PairedTextData` by `texar` seems to add by default PAD, BOS and EOS token at the beginning, after reading vocab.* file. These tokens have 0, 1, 2 indices respectively, and what's more important they change also GPT2 default tokens (each GPT2 token has index changed about 2-3 tokens further, for example, `<endoftext>` token is not 50256 like in the case of original GPT2, but 50260, etc.). 

Thanks in advance!

**Comment by HanGuo97** [comment]
The file format seems to be correct. A few notes:

1. We use the same vocabulary between the prompt model and the pretrained model.
2. As a side effect, since the prompt model uses different tokenization from the pretrained model, we have to pre-process the prompt targets further. The goal is that the processed targets are white-space tokenizable. In practice, this means running the targets through the pretrained model's tokenizer and save the subword-tokenized outputs as targets.

In case my description is unclear, I have attached the data used in our experiments below as a reference!
[pplm-gpt2.zip](https://github.com/HanGuo97/soft-Q-learning-for-text-generation/files/6764327/pplm-gpt2.zip)

**Comment by BartWolk** [comment]
Thanks! It works like the charm. I think you may include these reference data samples in the repository as the example inputs.
