### ISSUE TITLE
Further MLE baselines in the paper?

### ISSUE THREAD

**Issue by Shentao-YANG** [HanGuo97/soft-Q-learning-for-text-generation#9]
Hi,

Thank you for providing this wonderful repo!

We are very interested in your paper [Efficient (Soft) Q-Learning for Text Generation with Limited Good Data](https://arxiv.org/abs/2106.07704) and would like to replicate the experimental results therein.

We notice that in the paper you have some baselines that combine MLE training with the reward function, such as (1) using the reward function to filter examples; and (2) MLE weighted by rewards (page 6). However, we don't find implementations for these two baselines in this repo and don't quite know how to implement them ourselves. Specifically, since the paper assumes a sparse reward ( $r_t = 0, \\ \forall \ t < T$ on page 3), when using the rewards to weight the MLE, it appears that almost all the likelihood values will get a weight 0, i.e., $r_t \cdot \log \pi(a_t \mid s_t) = 0 \cdot \log \pi(a_t \mid s_t) = 0, \\ \forall \ t < T$. This problem seems to also hold for the MLE+reward baseline. 

Could you please kindly let us know how these two baselines can be implemented? 

Thank you so much!

**Comment by HanGuo97** [comment]
Hi Shentao,

Thanks for being interested in this work!

Those are good questions, and thanks for pointing out the confusion. For the filtering case, you could simply filter examples based on the rewards. For the weighting case, you could use the reward to weigh the loss. In both cases, they operate on the sequence level (instead of the token level).

Hope this helps!

**Comment by Shentao-YANG** [comment]
Thank you so much for the clarification. Yes, sequence-level rewards make sense to me!
